export const registrasiInitialValue = {
  nama_penanggung_jawab: "",
  nomor_penanggung_jawab: "",
  email_penanggung_jawab: "",
  jabatan_penanggung_jawab: "",
  nama: "",
  tanggal_berdiri: "",
  deskripsi: "",
  logo: null,
  telepon: "",
  provinsi: "",
  kota: "",
  kecamatan: "",
  alamat: "",
  kode_pos: "",
  email_perusahaan: "",
  website: "",
  npwp_perusahaan: null,
  legalitas_perusahaan: null,
  profil_background: null,
};
