export const data = [
    {
        id: 1,
        image: "https://i.pinimg.com/736x/6d/73/7d/6d737d825f8a2bcbd0b33e320cdc9f93.jpg",
        name: "Mybini",
        email: "Mybini@uhuy.com",
        asalsekolah: "SMKN FONTAIN",
    },
    {
        id: 2,
        image: "https://i.pinimg.com/1200x/32/36/f8/3236f89d3adf691b46ec0f1c0f4c88dd.jpg",
        name: "MyIstri",
        email: "MyIstri@uhuy.com",
        asalsekolah: "SMKN FONTAIN",
    },
    {
        id: 3,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 4,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 5,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 6,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 7,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 8,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 9,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 10,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 11,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 12,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 13,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 14,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 15,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 16,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 17,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 18,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 19,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },
   {
        id: 20,
        image: "/assets/img/Coba.png",
        name: "Mentor 3",
        email: "Mentor3@gmail.com",
        asalsekolah: "SMKN1 Bergembira",
    },

]