export const dummyPresentations = [
  {
    id: 1,
    tipe: "Offline",
    tanggal: "2025-12-10",
    waktu_mulai: "09:00",
    waktu_selesai: "11:00",
    status: "Dijadwalkan",
    kuota: 30,
    jumlah_pendaftar: 12,
    lokasi: "Ruang Rapat A, Lantai 2",
    link_zoom: null,
    catatan: "Bawa dokumen pendukung",
  },
  {
    id: 2,
    tipe: "Online",
    tanggal: "2025-12-08",
    waktu_mulai: "13:00",
    waktu_selesai: "15:00",
    status: "Selesai",
    kuota: 50,
    jumlah_pendaftar: 41,
    lokasi: null,
    link_zoom: "https://zoom.us/j/123456789",
    catatan: null,
  },
  {
    id: 3,
    tipe: "Offline",
    tanggal: "2025-12-05",
    waktu_mulai: "08:00",
    waktu_selesai: "10:00",
    status: "Selesai",
    kuota: 20,
    jumlah_pendaftar: 20,
    lokasi: "Ruang Aula Utama",
    link_zoom: null,
    catatan: null,
  },
  {
    id: 4,
    tipe: "Online",
    tanggal: "2025-12-01",
    waktu_mulai: "10:00",
    waktu_selesai: "11:30",
    status: "Dijadwalkan",
    kuota: 100,
    jumlah_pendaftar: 87,
    lokasi: null,
    link_zoom: "https://zoom.us/j/987654321",
    catatan: "Gunakan background formal",
  },
];
