export const ProfileSettingsFields = {
  dataCabang: [
    {
      name: "nama",
      label: "Nama Cabang",
      required: true,
      readonly: true,
      type: "input",
    },
    {
      name: "provinsi",
      label: "Provinsi",
      required: true,
      readonly: true,
      type: "input",
    },
    {
      name: "bidang_usaha",
      label: "Bidang Usaha",
      required: true,
      readonly: true,
      type: "input",
    },
    {
      name: "kota",
      label: "Kota",
      required: true,
      readonly: true,
      type: "input",
    },
    {
      name: "email",
      label: "Email",
      required: true,
      readonly: true,
      type: "input",
    },
    {
      name: "alamat",
      label: "Alamat",
      required: true,
      readonly: true,
      type: "input",
    },
  ],
  dataAdmin: [
    {
      name: "nama",
      label: "Nama",
      required: true,
      readonly: true,
      type: "input",
    },
    {
      name: "email",
      label: "Email",
      required: true,
      readonly: true,
      type: "input",
    },
    {
      name: "telepon",
      label: "Nomor HP",
      required: true,
      readonly: true,
      type: "input",
    },
    {
      name: "deskripsi",
      label: "Deskripsi",
      required: true,
      readonly: true,
      type: "textarea",
    },
  ],
  dataAdminEdit: [
    {
      name: "nama",
      label: "Nama",
      required: true,
      readonly: false,
      placeholder: "Masukkan Nama",
      type: "input",
    },
    {
      name: "email",
      label: "Email",
      placeholder: "Masukkan Email",
      required: true,
      readonly: false,
      type: "input",
    },
    {
      name: "telepon",
      label: "Nomor HP",
      required: true,
      placeholder: "Masukkan No. HP",
      readonly: false,
      type: "input",
    },
    {
      name: "d",
    },
    {
      name: "old_password",
      label: "Password Lama",
      placeholder: "Masukkan Password Lama",
      required: false,
      readonly: false,
      type: "password",
    },
    {
      name: "deskripsi",
      label: "Deskripsi",
      placeholder: "Masukkan Deskripsi",
      required: true,
      readonly: false,
      type: "textarea",
    },
    {
      name: "avatar",
      label: "Foto Profil Admin",
      placeholder: "Masukkan Foto Profil",
      required: "true",
      type: "file",
    },
    {
      name: "new_password",
      label: "Password Baru",
      placeholder: "Masukkan Password Baru",
      required: "false",
      type: "password",
    },
    {
      name: "confirm_password",
      label: "Konfirmasi Password Baru",
      placeholder: "Konfirmasi Password Baru",
      required: "false",
      type: "password",
    },
  ],
};
