import Logo from "./Logo.png"

const DummySuratPeringatan = [
  {
    id: 1,
    foto: Logo,
    nama: "Rudi Septiawan",
    sekolah: "SMK 3 Boyolali",
    keterangan: "Mewarnai Rambut",
    status: "SP 1",
    tanggal: "11 Juni 2022",
  },
  {
    id: 2,
    foto: Logo,
    nama: "Abdul Somat",
    sekolah: "SMK 7 Malang",
    keterangan: "Membuat Kegaduhan",
    status: "",
    tanggal: "26 Agustus 2023",
  },
  {
    id: 3,
    foto: Logo,
    nama: "Riki Prastyo",
    sekolah: "SMK 6 Jogjakarta",
    keterangan: "Melakukan Pemerasan",
    status: "SP 3",
    tanggal: "4 Oktober 2022",
  },
  {
    id: 4,
    foto: Logo,
    nama: "Siti Nurhaliza",
    sekolah: "SMK 5 Surabaya",
    keterangan: "Bolos sekolah",
    status: "SP 1",
    tanggal: "15 Januari 2023",
  },
  {
    id: 5,
    foto: Logo,
    nama: "Budi Santoso",
    sekolah: "SMK 2 Jakarta",
    keterangan: "Merokok di area sekolah",
    status: "SP 2",
    tanggal: "3 Maret 2023",
  },
  {
    id: 6,
    foto: Logo,
    nama: "Ani Wijaya",
    sekolah: "SMK 8 Bandung",
    keterangan: "Melakukan bullying",
    status: "SP 3",
    tanggal: "22 April 2023",
  },
  {
    id: 7,
    foto: Logo,
    nama: "Joko Susilo",
    sekolah: "SMK 4 Semarang",
    keterangan: "Membawa senjata tajam",
    status: "SP 1",
    tanggal: "7 Mei 2023",
  },
  {
    id: 8,
    foto: Logo,
    nama: "Dewi Lestari",
    sekolah: "SMK 9 Yogyakarta",
    keterangan: "Mencontek saat ujian",
    status: "SP 2",
    tanggal: "18 Juni 2023",
  },
  {
    id: 9,
    foto: Logo,
    nama: "Ahmad Fauzi",
    sekolah: "SMK 1 Medan",
    keterangan: "Melawan guru",
    status: "SP 3",
    tanggal: "30 Juli 2023",
  },
  {
    id: 10,
    foto: Logo,
    nama: "Maya Sari",
    sekolah: "SMK 10 Bali",
    keterangan: "Merusak fasilitas sekolah",
    status: "SP 1",
    tanggal: "12 Agustus 2023",
  },
  {
    id: 11,
    foto: Logo,
    nama: "Rizki Pratama",
    sekolah: "SMK 11 Makassar",
    keterangan: "Tidak memakai seragam",
    status: "SP 2",
    tanggal: "5 September 2023",
  },
  {
    id: 12,
    foto: Logo,
    nama: "Sari Dewi",
    sekolah: "SMK 12 Palembang",
    keterangan: "Terlambat berulang kali",
    status: "SP 1",
    tanggal: "21 Oktober 2023",
  },
  {
    id: 13,
    foto: Logo,
    nama: "Fajar Nugroho",
    sekolah: "SMK 13 Malang",
    keterangan: "Berbohong kepada guru",
    status: "SP 3",
    tanggal: "14 November 2023",
  },
  {
    id: 14,
    foto: Logo,
    nama: "Indah Permata",
    sekolah: "SMK 14 Solo",
    keterangan: "Menyontek tugas",
    status: "SP 2",
    tanggal: "9 Desember 2023",
  },
  {
    id: 15,
    foto: Logo,
    nama: "Hendra Kurniawan",
    sekolah: "SMK 15 Bogor",
    keterangan: "Membuat geng motor",
    status: "SP 3",
    tanggal: "25 Januari 2024",
  },
];

export default DummySuratPeringatan;