export const DataPesertaMagang = [
  {
    id: 1,
    nama: "Reivan Elsyafir Pratama",
    image: "/assets/img/post1.png",
    email: "hummatech@gmail.com",
    sekolah: "SMK 6 Muhammadiyah",
    status: "Aktif",
    tanggalAkhir: "12 - 12 - 2025",
    devisi: "UI/UX/Designer",
  },
  {
    id: 2,
    nama: "Reivan Elsyafir Pratama ",
    image: "/assets/img/post1.png",
    email: "hummatech@gmail.com",
    sekolah: "SMK 6 Muhammadiyah",
    status: "Alumni",
    tanggalAkhir: "12 - 12 - 2025",
    devisi: "UI/UX/Designer",
  },
  {
    id: 3,
    nama: "Reivan Elsyafir Pratama ",
    image: "/assets/img/post1.png",
    email: "hummatech@gmail.com",
    sekolah: "SMK 6 Muhammadiyah",
    status: "Aktif",
    tanggalAkhir: "12 - 12 - 2025",
    devisi: "UI/UX/Designer",
  },
  {
    id: 4,
    nama: "Reivan Elsyafir Pratama",
    image: "/assets/img/post1.png",
    email: "hummatech@gmail.com",
    sekolah: "SMK 6 Muhammadiyah",
    status: "Aktif",
    tanggalAkhir: "12 - 12 - 2025",
    devisi: "UI/UX/Designer",
  },
  {
    id: 5,
    nama: "Reivan Elsyafir Pratama",
    image: "/assets/img/post1.png",
    email: "hummatech@gmail.com",
    sekolah: "SMK 6 Muhammadiyah",
    status: "Aktif",
    tanggalAkhir: "12 - 12 - 2025",
    devisi: "UI/UX/Designer",
  },
];