export const dummyAdmin = [
    {
      nama: "Bagus Ahai",
      email: "boruto@gmail.com",
      masaMagang: "25 Januari 2025 - 25 Desember 2025",
      sekolah: "Smkn Ngasem Bojonegro",
    },
    {
      nama: "Siri Asik Uhuy",
      email: "lego@gmail.com",
      masaMagang: "10 Desember 2024 - 25 April 2025",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: " Ell King Mu",
      email: "alamak@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
    {
      nama: "Reivan Eliyafir Pratama",
      email: "bubuiboi@gmail.com",
      masaMagang: "25 Desember 2024 - 25 Desember 2035",
      sekolah: "Smkn Ngasem Bojonegoro",
    },
  ];