export const CabangDummy = [
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Aktif", cabang: "12", jumlah_peserta: "1,500" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Surabaya, Jawa Timur", status: "Aktif", cabang: "8", jumlah_peserta: "800" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Non Aktif", cabang: "5", jumlah_peserta: "450" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Surabaya, Jawa Timur", status: "Aktif", cabang: "10", jumlah_peserta: "1,200" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Non Aktif", cabang: "3", jumlah_peserta: "300" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Aktif", cabang: "12", jumlah_peserta: "1,500" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Surabaya, Jawa Timur", status: "Aktif", cabang: "8", jumlah_peserta: "800" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Non Aktif", cabang: "5", jumlah_peserta: "450" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Surabaya, Jawa Timur", status: "Aktif", cabang: "10", jumlah_peserta: "1,200" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Non Aktif", cabang: "3", jumlah_peserta: "300" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Aktif", cabang: "12", jumlah_peserta: "1,500" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Surabaya, Jawa Timur", status: "Aktif", cabang: "8", jumlah_peserta: "800" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Non Aktif", cabang: "5", jumlah_peserta: "450" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Surabaya, Jawa Timur", status: "Aktif", cabang: "10", jumlah_peserta: "1,200" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Non Aktif", cabang: "3", jumlah_peserta: "300" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Aktif", cabang: "12", jumlah_peserta: "1,500" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Surabaya, Jawa Timur", status: "Aktif", cabang: "8", jumlah_peserta: "800" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Non Aktif", cabang: "5", jumlah_peserta: "450" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Surabaya, Jawa Timur", status: "Aktif", cabang: "10", jumlah_peserta: "1,200" },
    { no: 1001, nama: "HUMMATECH", lokasi: "Malang, Jawa Timur", status: "Non Aktif", cabang: "3", jumlah_peserta: "300" },
  ];